### ISSUE TITLE
Automatically populate default values when creating new model

### ISSUE THREAD

**Issue by bigSiebs** [lewsid/dinkly#51]
It'd be nice if, when creating a new model instance, any default values that are set on insert are also set on the model instance.

For example, say we have the following config file:

```
table_name: dinkly_user
registry:
  - id
  - username: { type: varchar, length: 64, allow_null: false }
  - is_cool: { type: boolean, length: 1, allow_null: false, default: 1}
```

Then, somewhere in the code, we went to used the generated model for this table.
```
$user = new User($db);
$user->setUsername('CoolGuy1');
$user->save();
```

After saving, the `$user` object's `id` property has been set, but the `isCool` property is null, even though the record's field is set to 1 in the DB. It'd be nice if the model's property was automatically set to 1.

I think this could be implemented in one of two ways.

1) Add another property to the automatically generated base-prefixed model classes. You could call it `$defaults`. Then, when constructing a new model instance, any properties listed in this array would automatically be set equal to the default value.

2) Backfill the model after inserting. I'm not sure if there's a more efficient way to do it, but after inserting the record, you could run a select query using the `lastInsertId` and then populating the values into the model.
